package br.com.evolucao.evolucaoFisica.enumeration;

public enum TipoRegraGamificacao {
    TREINO_COMPLETO,
    TREINO_SEM_VONTADE,
    PROGRESSAO_REAL,
    PROTEINA_DIARIA,
    TREINOS_SEMANA,
    SONO_ADEQUADO,
    SONO_CONSISTENTE_SEMANA,
    RETORNO_APOS_PAUSA,
    REGISTRO_DIARIO,
    SEMANA_COMPLETA_REGISTRADA,
    DIAS_TREINADOS_TOTAL,
    PESO_ATINGIDO,
    CARGA_EXERCICIO_ATINGIDA,
    SEQUENCIA_ATUAL,
    TREINOS_SEM_VONTADE_TOTAL,
    PROGRESSOES_TOTAL,
    ALIMENTACAO_ALINHADA,
    DIAS_ALIMENTACAO_ALINHADA,
    RETORNOS_APOS_PAUSA_TOTAL,
    NIVEIS_SUBIDOS_TOTAL,
    REGISTROS_SEMANA,
    NIVEL_ATUAL,
    XP_TOTAL
}
