-- =========================================================
-- Arquivo: perfil_gamificacao_usuario.sql
-- Entidade: PerfilGamificacaoUsuario
-- Tabela: perfis_gamificacao_usuarios
-- Dependencias: usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS perfis_gamificacao_usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    data_inicio DATE NOT NULL,
    peso_inicial NUMERIC(10, 2),
    peso_atual NUMERIC(10, 2),
    treinos_realizados INTEGER NOT NULL DEFAULT 0,
    sequencia_atual INTEGER NOT NULL DEFAULT 0,
    melhor_sequencia INTEGER NOT NULL DEFAULT 0,
    dias_treinados_total INTEGER NOT NULL DEFAULT 0,
    treinos_sem_vontade_total INTEGER NOT NULL DEFAULT 0,
    progressoes_total INTEGER NOT NULL DEFAULT 0,
    dias_alimentacao_alinhada INTEGER NOT NULL DEFAULT 0,
    retornos_apos_pausa_total INTEGER NOT NULL DEFAULT 0,
    niveis_subidos_total INTEGER NOT NULL DEFAULT 0,
    xp_total INTEGER NOT NULL DEFAULT 0,
    nivel_atual INTEGER NOT NULL DEFAULT 1,
    tier_atual VARCHAR(20) NOT NULL DEFAULT 'BRONZE',
    ultima_data_treino DATE,
    ultima_data_registro DATE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_perfis_gamificacao_usuarios PRIMARY KEY (id),
    CONSTRAINT uk_perfis_gamificacao_usuario UNIQUE (usuario_id),
    CONSTRAINT fk_perfis_gamificacao_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT ck_perfis_gamificacao_tier CHECK (tier_atual IN ('BRONZE', 'PRATA', 'OURO', 'LENDA'))
);

CREATE INDEX IF NOT EXISTS idx_perfis_gamificacao_ranking
    ON perfis_gamificacao_usuarios (xp_total DESC, nivel_atual DESC);

CREATE INDEX IF NOT EXISTS idx_perfis_gamificacao_tier
    ON perfis_gamificacao_usuarios (tier_atual, xp_total DESC);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: perfil e criado a partir de usuario real.
