-- =========================================================
-- Arquivo: plano_alimentar_refeicao.sql
-- Entidade: PlanoAlimentarRefeicao
-- Tabela: planos_alimentares_refeicoes
-- Dependencias: planos_alimentares_dias
-- =========================================================

CREATE TABLE IF NOT EXISTS planos_alimentares_refeicoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    plano_dia_id BIGINT NOT NULL,
    tipo_refeicao VARCHAR(30) NOT NULL,
    horario_sugerido TIME,
    observacao VARCHAR(500),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_planos_alimentares_refeicoes PRIMARY KEY (id),
    CONSTRAINT fk_planos_alimentares_refeicoes_dia FOREIGN KEY (plano_dia_id) REFERENCES planos_alimentares_dias (id),
    CONSTRAINT ck_planos_alimentares_refeicoes_tipo CHECK (
        tipo_refeicao IN (
            'CAFE_DA_MANHA', 'CAFE_DA_TARDE', 'ALMOCO', 'JANTAR',
            'LANCHE', 'CEIA', 'PRE_TREINO', 'POS_TREINO'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_planos_alimentares_refeicoes_dia_tipo
    ON planos_alimentares_refeicoes (plano_dia_id, tipo_refeicao);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: refeicoes do plano dependem de input real.

