-- =========================================================
-- Arquivo: plano_alimentar_dia.sql
-- Entidade: PlanoAlimentarDia
-- Tabela: planos_alimentares_dias
-- Dependencias: planos_alimentares
-- =========================================================

CREATE TABLE IF NOT EXISTS planos_alimentares_dias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    plano_id BIGINT NOT NULL,
    dia_semana VARCHAR(20) NOT NULL,
    titulo VARCHAR(120) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_planos_alimentares_dias PRIMARY KEY (id),
    CONSTRAINT fk_planos_alimentares_dias_plano FOREIGN KEY (plano_id) REFERENCES planos_alimentares (id),
    CONSTRAINT ck_planos_alimentares_dias_dia_semana CHECK (
        dia_semana IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')
    )
);

CREATE INDEX IF NOT EXISTS idx_planos_alimentares_dias_plano_dia
    ON planos_alimentares_dias (plano_id, dia_semana);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: dias do plano dependem de input real.

