-- =========================================================
-- Arquivo: postagem_comentario.sql
-- Entidade: PostagemComentario
-- Tabela: postagens_comentarios
-- Dependencias: postagens, usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS postagens_comentarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    postagem_id BIGINT NOT NULL,
    autor_id BIGINT NOT NULL,
    conteudo VARCHAR(1000) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_postagens_comentarios PRIMARY KEY (id),
    CONSTRAINT fk_postagens_comentarios_postagem FOREIGN KEY (postagem_id) REFERENCES postagens (id),
    CONSTRAINT fk_postagens_comentarios_autor FOREIGN KEY (autor_id) REFERENCES usuarios (id)
);

CREATE INDEX IF NOT EXISTS idx_postagens_comentarios_postagem_criado_em
    ON postagens_comentarios (postagem_id, criado_em ASC);

CREATE INDEX IF NOT EXISTS idx_postagens_comentarios_autor_criado_em
    ON postagens_comentarios (autor_id, criado_em DESC);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: comentarios dependem de input real.

