-- =========================================================
-- Arquivo: registro_diario.sql
-- Entidade: RegistroDiario
-- Tabela: registros_diarios
-- Dependencias: usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS registros_diarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    plano_alimentar_id BIGINT,
    data_referencia DATE NOT NULL,
    realizou_treino BOOLEAN NOT NULL DEFAULT FALSE,
    tipo_treino VARCHAR(120),
    peso NUMERIC(10, 2),
    proteina_consumida NUMERIC(10, 2),
    bateu_proteina BOOLEAN NOT NULL DEFAULT FALSE,
    alimentacao_alinhada BOOLEAN NOT NULL DEFAULT FALSE,
    horas_sono NUMERIC(4, 2),
    houve_progressao BOOLEAN NOT NULL DEFAULT FALSE,
    descricao_progressao VARCHAR(500),
    motivacao VARCHAR(20) NOT NULL DEFAULT 'MEDIA',
    observacao VARCHAR(1000),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_registros_diarios PRIMARY KEY (id),
    CONSTRAINT uk_registro_diario_usuario_data UNIQUE (usuario_id, data_referencia),
    CONSTRAINT fk_registros_diarios_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_registros_diarios_plano_alimentar FOREIGN KEY (plano_alimentar_id) REFERENCES planos_alimentares (id),
    CONSTRAINT ck_registros_diarios_motivacao CHECK (motivacao IN ('ALTA', 'MEDIA', 'BAIXA'))
);

CREATE INDEX IF NOT EXISTS idx_registros_diarios_usuario_motivacao_treino
    ON registros_diarios (usuario_id, motivacao, realizou_treino);

CREATE INDEX IF NOT EXISTS idx_registros_diarios_usuario_progressao
    ON registros_diarios (usuario_id, houve_progressao);

CREATE INDEX IF NOT EXISTS idx_registros_diarios_usuario_alimentacao
    ON registros_diarios (usuario_id, alimentacao_alinhada);

CREATE INDEX IF NOT EXISTS idx_registros_diarios_usuario_data_plano
    ON registros_diarios (usuario_id, data_referencia DESC, plano_alimentar_id);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: registros diarios dependem de input real.

