-- =========================================================
-- Arquivo: registro_exercicio.sql
-- Entidade: RegistroExercicio
-- Tabela: registro_exercicios
-- Dependencias: registros_treino, exercicios
-- =========================================================

CREATE TABLE IF NOT EXISTS registro_exercicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    registro_treino_id BIGINT NOT NULL,
    exercicio_id BIGINT NOT NULL,
    carga_real NUMERIC(10, 2),
    repeticoes_real INTEGER NOT NULL,
    concluido BOOLEAN NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_registro_exercicios PRIMARY KEY (id),
    CONSTRAINT fk_registro_exercicios_registro_treino FOREIGN KEY (registro_treino_id) REFERENCES registros_treino (id),
    CONSTRAINT fk_registro_exercicios_exercicio FOREIGN KEY (exercicio_id) REFERENCES exercicios (id)
);

CREATE INDEX IF NOT EXISTS idx_registro_exercicios_registro
    ON registro_exercicios (registro_treino_id, id);

CREATE INDEX IF NOT EXISTS idx_registro_exercicios_exercicio
    ON registro_exercicios (exercicio_id);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: execucao depende de evento real.

