-- =========================================================
-- Arquivo: registro_treino.sql
-- Entidade: RegistroTreino
-- Tabela: registros_treino
-- Dependencias: usuarios, treinos
-- =========================================================

CREATE TABLE IF NOT EXISTS registros_treino (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    treino_id BIGINT NOT NULL,
    data_registro TIMESTAMP NOT NULL,
    finalizado_em TIMESTAMP,
    observacao VARCHAR(500),
    motivacao VARCHAR(20),
    concluido BOOLEAN NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_registros_treino PRIMARY KEY (id),
    CONSTRAINT fk_registros_treino_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_registros_treino_treino FOREIGN KEY (treino_id) REFERENCES treinos (id),
    CONSTRAINT ck_registros_treino_motivacao CHECK (
        motivacao IS NULL OR motivacao IN ('ALTA', 'MEDIA', 'BAIXA')
    )
);

CREATE INDEX IF NOT EXISTS idx_registros_treino_usuario_data
    ON registros_treino (usuario_id, data_registro DESC);

CREATE INDEX IF NOT EXISTS idx_registros_treino_usuario_concluido_data
    ON registros_treino (usuario_id, concluido, data_registro ASC);

CREATE INDEX IF NOT EXISTS idx_registros_treino_treino
    ON registros_treino (treino_id);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: registros de treino dependem de evento real.

