-- =========================================================
-- Arquivo: seguidor.sql
-- Entidade: Seguidor
-- Tabela: seguidores
-- Dependencias: usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS seguidores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    seguidor_id BIGINT NOT NULL,
    seguido_id BIGINT NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_seguidores PRIMARY KEY (id),
    CONSTRAINT uk_seguidor_seguido UNIQUE (seguidor_id, seguido_id),
    CONSTRAINT fk_seguidores_seguidor FOREIGN KEY (seguidor_id) REFERENCES usuarios (id),
    CONSTRAINT fk_seguidores_seguido FOREIGN KEY (seguido_id) REFERENCES usuarios (id)
);

CREATE INDEX IF NOT EXISTS idx_seguidores_seguidor_ativo
    ON seguidores (seguidor_id, ativo);

CREATE INDEX IF NOT EXISTS idx_seguidores_seguido_ativo
    ON seguidores (seguido_id, ativo);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: relacionamentos sociais dependem de evento real.

