-- =========================================================
-- Arquivo: treino.sql
-- Entidade: Treino
-- Tabela: treinos
-- Dependencias: usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS treinos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(120) NOT NULL,
    descricao VARCHAR(500),
    observacoes VARCHAR(500),
    tipo_treino VARCHAR(20) NOT NULL,
    usuario_id BIGINT NOT NULL,
    dia_semana VARCHAR(20),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    publico BOOLEAN NOT NULL DEFAULT FALSE,
    recorrente BOOLEAN NOT NULL DEFAULT TRUE,
    data_treino TIMESTAMP NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_treinos PRIMARY KEY (id),
    CONSTRAINT fk_treinos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT ck_treinos_tipo CHECK (tipo_treino IN ('A', 'B', 'C', 'FULL_BODY')),
    CONSTRAINT ck_treinos_dia_semana CHECK (
        dia_semana IS NULL OR dia_semana IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')
    )
);

CREATE INDEX IF NOT EXISTS idx_treinos_usuario_data
    ON treinos (usuario_id, data_treino DESC);

CREATE INDEX IF NOT EXISTS idx_treinos_usuario_ativo
    ON treinos (usuario_id, ativo, publico);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: treinos dependem de input real.

