-- =========================================================
-- Arquivo: treino_exercicio.sql
-- Entidade: TreinoExercicio
-- Tabela: treino_exercicios
-- Dependencias: treinos, exercicios
-- =========================================================

CREATE TABLE IF NOT EXISTS treino_exercicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    treino_id BIGINT NOT NULL,
    exercicio_id BIGINT NOT NULL,
    series INTEGER NOT NULL,
    repeticoes INTEGER NOT NULL,
    carga NUMERIC(10, 2),
    dificuldade VARCHAR(20) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_treino_exercicios PRIMARY KEY (id),
    CONSTRAINT fk_treino_exercicios_treino FOREIGN KEY (treino_id) REFERENCES treinos (id),
    CONSTRAINT fk_treino_exercicios_exercicio FOREIGN KEY (exercicio_id) REFERENCES exercicios (id),
    CONSTRAINT ck_treino_exercicios_dificuldade CHECK (dificuldade IN ('LEVE', 'MODERADA', 'ALTA'))
);

CREATE INDEX IF NOT EXISTS idx_treino_exercicios_treino
    ON treino_exercicios (treino_id, id);

CREATE INDEX IF NOT EXISTS idx_treino_exercicios_exercicio
    ON treino_exercicios (exercicio_id);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: associacao depende de input real.

