-- =========================================================
-- Arquivo: usuario_missao_semanal.sql
-- Entidade: UsuarioMissaoSemanal
-- Tabela: usuarios_missoes_semanais
-- Dependencias: usuarios, missoes_semanais
-- =========================================================

CREATE TABLE IF NOT EXISTS usuarios_missoes_semanais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    missao_id BIGINT NOT NULL,
    semana_referencia DATE NOT NULL,
    progresso NUMERIC(12, 2) NOT NULL DEFAULT 0,
    concluida BOOLEAN NOT NULL DEFAULT FALSE,
    total_conclusoes INTEGER NOT NULL DEFAULT 0,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_usuarios_missoes_semanais PRIMARY KEY (id),
    CONSTRAINT uk_usuario_missao_semana UNIQUE (usuario_id, missao_id, semana_referencia),
    CONSTRAINT fk_usuarios_missoes_semanais_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_usuarios_missoes_semanais_missao FOREIGN KEY (missao_id) REFERENCES missoes_semanais (id)
);

CREATE INDEX IF NOT EXISTS idx_usuarios_missoes_semanais_usuario_semana
    ON usuarios_missoes_semanais (usuario_id, semana_referencia);

CREATE INDEX IF NOT EXISTS idx_usuarios_missoes_semanais_missao_semana
    ON usuarios_missoes_semanais (missao_id, semana_referencia);

CREATE INDEX IF NOT EXISTS idx_usuarios_missoes_semanais_concluida
    ON usuarios_missoes_semanais (usuario_id, missao_id, concluida);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: progresso semanal depende de evento real.

