DROP TABLE IF EXISTS alimentos CASCADE;

-- =========================================================
-- Arquivo: alimento.sql
-- Entidade: Alimento
-- Tabela: alimentos
-- Dependencias: nenhuma
-- =========================================================

CREATE TABLE IF NOT EXISTS alimentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(120) NOT NULL,
    calorias NUMERIC(10, 2) NOT NULL,
    proteina NUMERIC(10, 2) NOT NULL,
    carboidrato NUMERIC(10, 2) NOT NULL,
    gordura NUMERIC(10, 2) NOT NULL,
    acucares NUMERIC(10, 2) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_alimentos PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_alimentos_nome
    ON alimentos (nome);

CREATE INDEX IF NOT EXISTS idx_alimentos_lower_nome
    ON alimentos (LOWER(nome));

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: catalogo depende de input real/admin.


