DROP TABLE IF EXISTS evolucoes_fisicas CASCADE;

-- =========================================================
-- Arquivo: evolucao_fisica.sql
-- Entidade: EvolucaoFisica
-- Tabela: evolucoes_fisicas
-- Dependencias: usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS evolucoes_fisicas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    peso NUMERIC(10, 2) NOT NULL,
    percentual_gordura NUMERIC(10, 2),
    massa_magra NUMERIC(10, 2),
    data_registro TIMESTAMP NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_evolucoes_fisicas PRIMARY KEY (id),
    CONSTRAINT fk_evolucoes_fisicas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE INDEX IF NOT EXISTS idx_evolucoes_fisicas_usuario_data
    ON evolucoes_fisicas (usuario_id, data_registro DESC);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: evolucao fisica depende de input real.


