-- =========================================================
-- Arquivo: exercicio.sql
-- Entidade: Exercicio
-- Tabela: exercicios
-- Dependencias: nenhuma
-- =========================================================

CREATE TABLE IF NOT EXISTS exercicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(120) NOT NULL,
    grupo_muscular VARCHAR(60) NOT NULL,
    equipamento VARCHAR(80),
    descricao VARCHAR(500),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_exercicios PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_exercicios_nome
    ON exercicios (nome);

CREATE INDEX IF NOT EXISTS idx_exercicios_lower_nome
    ON exercicios (LOWER(nome));

CREATE INDEX IF NOT EXISTS idx_exercicios_grupo_muscular
    ON exercicios (grupo_muscular);

CREATE INDEX IF NOT EXISTS idx_exercicios_equipamento
    ON exercicios (equipamento);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: exercicios dependem de input real/admin.

