DROP TABLE IF EXISTS grupos CASCADE;

-- =========================================================
-- Arquivo: grupo.sql
-- Entidade: Grupo
-- Tabela: grupos
-- Dependencias: usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS grupos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(120) NOT NULL,
    descricao VARCHAR(500),
    criador_id BIGINT NOT NULL,
    visibilidade VARCHAR(20) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_grupos PRIMARY KEY (id),
    CONSTRAINT fk_grupos_criador FOREIGN KEY (criador_id) REFERENCES usuarios (id),
    CONSTRAINT ck_grupos_visibilidade CHECK (visibilidade IN ('PUBLICA', 'SEGUIDORES', 'GRUPO', 'PRIVADA'))
);

CREATE INDEX IF NOT EXISTS idx_grupos_criador_ativo
    ON grupos (criador_id, ativo);

CREATE INDEX IF NOT EXISTS idx_grupos_visibilidade_ativo
    ON grupos (visibilidade, ativo);

CREATE INDEX IF NOT EXISTS idx_grupos_nome
    ON grupos (nome);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: grupos dependem de input real do usuario.


