-- =========================================================
-- Arquivo: grupo_membro.sql
-- Entidade: GrupoMembro
-- Tabela: grupos_membros
-- Dependencias: grupos, usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS grupos_membros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    grupo_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_grupos_membros PRIMARY KEY (id),
    CONSTRAINT uk_grupo_usuario UNIQUE (grupo_id, usuario_id),
    CONSTRAINT fk_grupos_membros_grupo FOREIGN KEY (grupo_id) REFERENCES grupos (id),
    CONSTRAINT fk_grupos_membros_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT ck_grupos_membros_role CHECK (role IN ('DONO', 'ADMIN', 'MEMBRO'))
);

CREATE INDEX IF NOT EXISTS idx_grupos_membros_usuario_ativo
    ON grupos_membros (usuario_id, ativo);

CREATE INDEX IF NOT EXISTS idx_grupos_membros_grupo_ativo
    ON grupos_membros (grupo_id, ativo);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: vinculo depende de evento real do usuario.

