-- =========================================================
-- Arquivo: medalha.sql
-- Entidade: Medalha
-- Tabela: medalhas
-- Dependencias: nenhuma
-- =========================================================

CREATE TABLE IF NOT EXISTS medalhas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(120) NOT NULL,
    descricao VARCHAR(500),
    tipo VARCHAR(20) NOT NULL,
    tipo_regra VARCHAR(50) NOT NULL,
    valor_meta NUMERIC(12, 2) NOT NULL,
    valor_referencia VARCHAR(120),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_medalhas PRIMARY KEY (id),
    CONSTRAINT uk_medalhas_nome UNIQUE (nome),
    CONSTRAINT ck_medalhas_tipo CHECK (tipo IN ('UNICA', 'REPETIVEL')),
    CONSTRAINT ck_medalhas_tipo_regra CHECK (
        tipo_regra IN (
            'TREINO_COMPLETO', 'TREINO_SEM_VONTADE', 'PROGRESSAO_REAL', 'PROTEINA_DIARIA',
            'TREINOS_SEMANA', 'SONO_ADEQUADO', 'SONO_CONSISTENTE_SEMANA', 'RETORNO_APOS_PAUSA',
            'REGISTRO_DIARIO', 'SEMANA_COMPLETA_REGISTRADA', 'DIAS_TREINADOS_TOTAL',
            'PESO_ATINGIDO', 'CARGA_EXERCICIO_ATINGIDA', 'SEQUENCIA_ATUAL',
            'TREINOS_SEM_VONTADE_TOTAL', 'PROGRESSOES_TOTAL', 'ALIMENTACAO_ALINHADA',
            'DIAS_ALIMENTACAO_ALINHADA', 'RETORNOS_APOS_PAUSA_TOTAL', 'NIVEIS_SUBIDOS_TOTAL',
            'REGISTROS_SEMANA', 'NIVEL_ATUAL', 'XP_TOTAL'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_medalhas_ativo_nome
    ON medalhas (ativo, nome);

CREATE INDEX IF NOT EXISTS idx_medalhas_tipo_regra
    ON medalhas (tipo_regra, ativo);

-- Carga inicial derivada do bootstrap da aplicacao
INSERT INTO medalhas (nome, descricao, tipo, tipo_regra, valor_meta, valor_referencia, ativo, criado_em, atualizado_em)
VALUES
    ('3 meses', '3 meses', 'UNICA', 'DIAS_TREINADOS_TOTAL', 90, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('6 meses', '6 meses', 'UNICA', 'DIAS_TREINADOS_TOTAL', 180, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('1 ano', '1 ano', 'UNICA', 'DIAS_TREINADOS_TOTAL', 365, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('77kg atingido', '77kg atingido', 'UNICA', 'PESO_ATINGIDO', 77, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('80kg atingido', '80kg atingido', 'UNICA', 'PESO_ATINGIDO', 80, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Supino 30kg', 'Supino 30kg', 'UNICA', 'CARGA_EXERCICIO_ATINGIDA', 30, 'Supino', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Supino 40kg', 'Supino 40kg', 'UNICA', 'CARGA_EXERCICIO_ATINGIDA', 40, 'Supino', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Supino 50kg', 'Supino 50kg', 'UNICA', 'CARGA_EXERCICIO_ATINGIDA', 50, 'Supino', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Consistencia Brutal', 'Consistencia Brutal', 'REPETIVEL', 'SEQUENCIA_ATUAL', 15, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Treinei sem vontade', 'Treinei sem vontade', 'REPETIVEL', 'TREINOS_SEM_VONTADE_TOTAL', 1, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Progressao Real', 'Progressao Real', 'REPETIVEL', 'PROGRESSOES_TOTAL', 1, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Dieta Alinhada', 'Dieta Alinhada', 'REPETIVEL', 'DIAS_ALIMENTACAO_ALINHADA', 1, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Voltei Mais Forte', 'Voltei Mais Forte', 'REPETIVEL', 'RETORNOS_APOS_PAUSA_TOTAL', 1, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Subi de nivel', 'Subi de nivel', 'REPETIVEL', 'NIVEIS_SUBIDOS_TOTAL', 1, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (nome) DO NOTHING;

