DROP TABLE IF EXISTS metas_atletas CASCADE;

-- =========================================================
-- Arquivo: meta_atleta.sql
-- Entidade: MetaAtleta
-- Tabela: metas_atletas
-- Dependencias: usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS metas_atletas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    frequencia_semanal_meta INTEGER,
    proteina_diaria_meta NUMERIC(10, 2),
    caloria_diaria_meta NUMERIC(10, 2),
    observacao VARCHAR(300),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_metas_atletas PRIMARY KEY (id),
    CONSTRAINT uk_metas_atletas_usuario UNIQUE (usuario_id),
    CONSTRAINT fk_metas_atletas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: metas dependem de input real do atleta.


