DROP TABLE IF EXISTS missoes_semanais CASCADE;

-- =========================================================
-- Arquivo: missao_semanal.sql
-- Entidade: MissaoSemanal
-- Tabela: missoes_semanais
-- Dependencias: nenhuma
-- =========================================================

CREATE TABLE IF NOT EXISTS missoes_semanais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(120) NOT NULL,
    descricao VARCHAR(500),
    tipo_regra VARCHAR(50) NOT NULL,
    meta_valor NUMERIC(12, 2) NOT NULL,
    xp_recompensa INTEGER NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_missoes_semanais PRIMARY KEY (id),
    CONSTRAINT uk_missoes_semanais_nome UNIQUE (nome),
    CONSTRAINT ck_missoes_semanais_tipo_regra CHECK (
        tipo_regra IN (
            'TREINO_COMPLETO', 'TREINO_SEM_VONTADE', 'PROGRESSAO_REAL', 'PROTEINA_DIARIA',
            'TREINOS_SEMANA', 'SONO_ADEQUADO', 'SONO_CONSISTENTE_SEMANA', 'RETORNO_APOS_PAUSA',
            'REGISTRO_DIARIO', 'SEMANA_COMPLETA_REGISTRADA', 'DIAS_TREINADOS_TOTAL',
            'PESO_ATINGIDO', 'CARGA_EXERCICIO_ATINGIDA', 'SEQUENCIA_ATUAL',
            'TREINOS_SEM_VONTADE_TOTAL', 'PROGRESSOES_TOTAL', 'ALIMENTACAO_ALINHADA',
            'DIAS_ALIMENTACAO_ALINHADA', 'RETORNOS_APOS_PAUSA_TOTAL', 'NIVEIS_SUBIDOS_TOTAL',
            'REGISTROS_SEMANA', 'NIVEL_ATUAL', 'XP_TOTAL'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_missoes_semanais_ativo_nome
    ON missoes_semanais (ativo, nome);

CREATE INDEX IF NOT EXISTS idx_missoes_semanais_tipo_regra
    ON missoes_semanais (tipo_regra, ativo);

-- Carga inicial derivada do bootstrap da aplicacao
INSERT INTO missoes_semanais (nome, descricao, tipo_regra, meta_valor, xp_recompensa, ativo, criado_em, atualizado_em)
VALUES
    ('Treinar 5 dias', 'Treinar 5 dias', 'TREINOS_SEMANA', 5, 250, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Bater proteina diaria', 'Bater proteina diaria', 'PROTEINA_DIARIA', 5, 100, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Progredir carga ou reps', 'Progredir carga ou reps', 'PROGRESSAO_REAL', 1, 100, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Dormir 7-8 horas', 'Dormir 7-8 horas', 'SONO_CONSISTENTE_SEMANA', 5, 80, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Registrar o dia', 'Registrar o dia', 'REGISTROS_SEMANA', 5, 50, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (nome) DO NOTHING;


