DROP TABLE IF EXISTS niveis CASCADE;

-- =========================================================
-- Arquivo: nivel.sql
-- Entidade: Nivel
-- Tabela: niveis
-- Dependencias: nenhuma
-- =========================================================

CREATE TABLE IF NOT EXISTS niveis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    numero INTEGER NOT NULL,
    xp_necessario INTEGER NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_niveis PRIMARY KEY (id),
    CONSTRAINT uk_nivel_numero UNIQUE (numero)
);

CREATE INDEX IF NOT EXISTS idx_niveis_xp_necessario
    ON niveis (xp_necessario);

-- Carga inicial baseada na regra de nivelamento do sistema
WITH RECURSIVE niveis_seed AS (
    SELECT 1 AS numero, 0 AS xp_necessario
    UNION ALL
    SELECT numero + 1,
           xp_necessario + (500 + (numero * 250))
    FROM niveis_seed
    WHERE numero < 30
)
INSERT INTO niveis (numero, xp_necessario, criado_em, atualizado_em)
SELECT numero, xp_necessario, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM niveis_seed
ON CONFLICT (numero) DO NOTHING;


