DROP TABLE IF EXISTS planos_alimentares CASCADE;

-- =========================================================
-- Arquivo: plano_alimentar.sql
-- Entidade: PlanoAlimentar
-- Tabela: planos_alimentares
-- Dependencias: usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS planos_alimentares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    nome VARCHAR(120) NOT NULL,
    descricao VARCHAR(500),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    publico BOOLEAN NOT NULL DEFAULT FALSE,
    principal BOOLEAN NOT NULL DEFAULT FALSE,
    data_inicio DATE,
    data_fim DATE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_planos_alimentares PRIMARY KEY (id),
    CONSTRAINT fk_planos_alimentares_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE INDEX IF NOT EXISTS idx_planos_alimentares_usuario
    ON planos_alimentares (usuario_id, ativo);

CREATE INDEX IF NOT EXISTS idx_planos_alimentares_publico
    ON planos_alimentares (publico, ativo);

CREATE INDEX IF NOT EXISTS idx_planos_alimentares_usuario_principal
    ON planos_alimentares (usuario_id, principal, ativo);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: plano alimentar depende de input real.


