DROP TABLE IF EXISTS planos_alimentares_refeicoes_alimentos CASCADE;

-- =========================================================
-- Arquivo: plano_alimentar_refeicao_alimento.sql
-- Entidade: PlanoAlimentarRefeicaoAlimento
-- Tabela: planos_alimentares_refeicoes_alimentos
-- Dependencias: planos_alimentares_refeicoes, alimentos
-- =========================================================

CREATE TABLE IF NOT EXISTS planos_alimentares_refeicoes_alimentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    plano_refeicao_id BIGINT NOT NULL,
    alimento_id BIGINT NOT NULL,
    quantidade NUMERIC(10, 2) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_planos_alimentares_refeicoes_alimentos PRIMARY KEY (id),
    CONSTRAINT fk_planos_alimentares_refeicoes_alimentos_refeicao FOREIGN KEY (plano_refeicao_id) REFERENCES planos_alimentares_refeicoes (id),
    CONSTRAINT fk_planos_alimentares_refeicoes_alimentos_alimento FOREIGN KEY (alimento_id) REFERENCES alimentos (id)
);

CREATE INDEX IF NOT EXISTS idx_planos_alimentares_refeicoes_alimentos_refeicao
    ON planos_alimentares_refeicoes_alimentos (plano_refeicao_id);

CREATE INDEX IF NOT EXISTS idx_planos_alimentares_refeicoes_alimentos_alimento
    ON planos_alimentares_refeicoes_alimentos (alimento_id);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: composicao do plano depende de input real.


