-- =========================================================
-- Arquivo: postagem_curtida.sql
-- Entidade: PostagemCurtida
-- Tabela: postagens_curtidas
-- Dependencias: postagens, usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS postagens_curtidas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    postagem_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_postagens_curtidas PRIMARY KEY (id),
    CONSTRAINT uk_postagem_usuario_curtida UNIQUE (postagem_id, usuario_id),
    CONSTRAINT fk_postagens_curtidas_postagem FOREIGN KEY (postagem_id) REFERENCES postagens (id),
    CONSTRAINT fk_postagens_curtidas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE INDEX IF NOT EXISTS idx_postagens_curtidas_usuario
    ON postagens_curtidas (usuario_id);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: curtidas dependem de evento real.

