DROP TABLE IF EXISTS postagens CASCADE;

-- =========================================================
-- Arquivo: postagem.sql
-- Entidade: Postagem
-- Tabela: postagens
-- Dependencias: usuarios, grupos, registros_treino, evolucoes_fisicas
-- =========================================================

CREATE TABLE IF NOT EXISTS postagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    autor_id BIGINT NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    visibilidade VARCHAR(20) NOT NULL,
    grupo_id BIGINT,
    registro_treino_id BIGINT,
    evolucao_fisica_id BIGINT,
    conteudo VARCHAR(2000),
    midia_url VARCHAR(500),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_postagens PRIMARY KEY (id),
    CONSTRAINT fk_postagens_autor FOREIGN KEY (autor_id) REFERENCES usuarios (id),
    CONSTRAINT fk_postagens_grupo FOREIGN KEY (grupo_id) REFERENCES grupos (id),
    CONSTRAINT fk_postagens_registro_treino FOREIGN KEY (registro_treino_id) REFERENCES registros_treino (id),
    CONSTRAINT fk_postagens_evolucao_fisica FOREIGN KEY (evolucao_fisica_id) REFERENCES evolucoes_fisicas (id),
    CONSTRAINT ck_postagens_tipo CHECK (tipo IN ('TREINO', 'DIETA', 'EVOLUCAO', 'TEXTO', 'FOTO')),
    CONSTRAINT ck_postagens_visibilidade CHECK (visibilidade IN ('PUBLICA', 'SEGUIDORES', 'GRUPO', 'PRIVADA'))
);

CREATE INDEX IF NOT EXISTS idx_postagens_autor_criado_em
    ON postagens (autor_id, criado_em DESC);

CREATE INDEX IF NOT EXISTS idx_postagens_grupo_criado_em
    ON postagens (grupo_id, criado_em DESC);

CREATE INDEX IF NOT EXISTS idx_postagens_visibilidade_ativo
    ON postagens (visibilidade, ativo, criado_em DESC);

CREATE INDEX IF NOT EXISTS idx_postagens_registro_treino
    ON postagens (registro_treino_id);

CREATE INDEX IF NOT EXISTS idx_postagens_evolucao_fisica
    ON postagens (evolucao_fisica_id);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: postagens dependem de evento real.


