-- =========================================================
-- Arquivo: refeicao.sql
-- Entidade: Refeicao
-- Tabela: refeicoes
-- Dependencias: usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS refeicoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    data TIMESTAMP NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_refeicoes PRIMARY KEY (id),
    CONSTRAINT fk_refeicoes_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT ck_refeicoes_tipo CHECK (
        tipo IN (
            'CAFE_DA_MANHA', 'CAFE_DA_TARDE', 'ALMOCO', 'JANTAR',
            'LANCHE', 'CEIA', 'PRE_TREINO', 'POS_TREINO'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_refeicoes_usuario_data
    ON refeicoes (usuario_id, data DESC);

CREATE INDEX IF NOT EXISTS idx_refeicoes_usuario_tipo_data
    ON refeicoes (usuario_id, tipo, data DESC);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: refeicoes dependem de input real.

