DROP TABLE IF EXISTS refeicao_alimentos CASCADE;

-- =========================================================
-- Arquivo: refeicao_alimento.sql
-- Entidade: RefeicaoAlimento
-- Tabela: refeicao_alimentos
-- Dependencias: refeicoes, alimentos
-- =========================================================

CREATE TABLE IF NOT EXISTS refeicao_alimentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    refeicao_id BIGINT NOT NULL,
    alimento_id BIGINT NOT NULL,
    quantidade NUMERIC(10, 2) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_refeicao_alimentos PRIMARY KEY (id),
    CONSTRAINT fk_refeicao_alimentos_refeicao FOREIGN KEY (refeicao_id) REFERENCES refeicoes (id),
    CONSTRAINT fk_refeicao_alimentos_alimento FOREIGN KEY (alimento_id) REFERENCES alimentos (id)
);

CREATE INDEX IF NOT EXISTS idx_refeicao_alimentos_refeicao
    ON refeicao_alimentos (refeicao_id);

CREATE INDEX IF NOT EXISTS idx_refeicao_alimentos_alimento
    ON refeicao_alimentos (alimento_id);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: composicao da refeicao depende de input real.


