DROP TABLE IF EXISTS usuarios_medalhas CASCADE;

-- =========================================================
-- Arquivo: usuario_medalha.sql
-- Entidade: UsuarioMedalha
-- Tabela: usuarios_medalhas
-- Dependencias: usuarios, medalhas
-- =========================================================

CREATE TABLE IF NOT EXISTS usuarios_medalhas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    medalha_id BIGINT NOT NULL,
    quantidade INTEGER NOT NULL DEFAULT 0,
    ultima_conquista_em TIMESTAMP,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_usuarios_medalhas PRIMARY KEY (id),
    CONSTRAINT uk_usuario_medalha UNIQUE (usuario_id, medalha_id),
    CONSTRAINT fk_usuarios_medalhas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_usuarios_medalhas_medalha FOREIGN KEY (medalha_id) REFERENCES medalhas (id)
);

CREATE INDEX IF NOT EXISTS idx_usuarios_medalhas_usuario
    ON usuarios_medalhas (usuario_id, ultima_conquista_em DESC);

CREATE INDEX IF NOT EXISTS idx_usuarios_medalhas_medalha
    ON usuarios_medalhas (medalha_id);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: concessao depende de evento real.


