DROP TABLE IF EXISTS usuarios_identidades_externas CASCADE;

-- =========================================================
-- Arquivo: usuario_identidade_externa.sql
-- Entidade: UsuarioIdentidadeExterna
-- Tabela: usuarios_identidades_externas
-- Dependencias: usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS usuarios_identidades_externas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    provedor VARCHAR(30) NOT NULL,
    identificador_externo VARCHAR(150) NOT NULL,
    email_externo VARCHAR(150),
    nome_exibicao VARCHAR(120),
    foto_perfil_url VARCHAR(500),
    ultimo_login_em TIMESTAMP,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_usuarios_identidades_externas PRIMARY KEY (id),
    CONSTRAINT uk_provedor_identificador_externo UNIQUE (provedor, identificador_externo),
    CONSTRAINT fk_usuarios_identidades_externas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT ck_usuarios_identidades_externas_provedor CHECK (provedor IN ('GOOGLE'))
);

CREATE INDEX IF NOT EXISTS idx_usuarios_identidades_externas_usuario
    ON usuarios_identidades_externas (usuario_id);

CREATE INDEX IF NOT EXISTS idx_usuarios_identidades_externas_email
    ON usuarios_identidades_externas (email_externo);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: identidades externas dependem de vinculacao real.


