-- =========================================================
-- Arquivo: usuario.sql
-- Entidade: Usuario
-- Tabela: usuarios
-- Dependencias: nenhuma
-- =========================================================

CREATE TABLE IF NOT EXISTS usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    username VARCHAR(50) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    telefone VARCHAR(20),
    bio VARCHAR(500),
    foto_perfil_url VARCHAR(500),
    peso_atual NUMERIC(10, 2),
    altura NUMERIC(10, 2),
    objetivo VARCHAR(30) NOT NULL,
    data_nascimento DATE,
    cidade VARCHAR(100),
    estado VARCHAR(100),
    perfil_privado BOOLEAN NOT NULL DEFAULT FALSE,
    role_sistema VARCHAR(20) NOT NULL DEFAULT 'USUARIO',
    data_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_usuarios PRIMARY KEY (id),
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT uk_usuarios_username UNIQUE (username),
    CONSTRAINT ck_usuarios_objetivo CHECK (objetivo IN ('GANHO_MASSA', 'DEFINICAO', 'MANUTENCAO', 'EMAGRECIMENTO')),
    CONSTRAINT ck_usuarios_role_sistema CHECK (role_sistema IN ('ADMIN', 'GESTOR', 'USUARIO'))
);

CREATE INDEX IF NOT EXISTS idx_usuarios_objetivo_ativo
    ON usuarios (objetivo, ativo);

CREATE INDEX IF NOT EXISTS idx_usuarios_role_sistema_ativo
    ON usuarios (role_sistema, ativo);

CREATE INDEX IF NOT EXISTS idx_usuarios_data_criacao
    ON usuarios (data_criacao DESC);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: usuarios dependem de input real.



-- =========================================================
-- Arquivo: nivel.sql
-- Entidade: Nivel
-- Tabela: niveis
-- Dependencias: nenhuma
-- =========================================================

CREATE TABLE IF NOT EXISTS niveis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    numero INTEGER NOT NULL,
    xp_necessario INTEGER NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_niveis PRIMARY KEY (id),
    CONSTRAINT uk_nivel_numero UNIQUE (numero)
);

CREATE INDEX IF NOT EXISTS idx_niveis_xp_necessario
    ON niveis (xp_necessario);

-- Carga inicial baseada na regra de nivelamento do sistema
WITH RECURSIVE niveis_seed AS (
    SELECT 1 AS numero, 0 AS xp_necessario
    UNION ALL
    SELECT numero + 1,
           xp_necessario + (500 + (numero * 250))
    FROM niveis_seed
    WHERE numero < 30
)
INSERT INTO niveis (numero, xp_necessario, criado_em, atualizado_em)
SELECT numero, xp_necessario, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM niveis_seed
ON CONFLICT (numero) DO NOTHING;



-- =========================================================
-- Arquivo: xp_regra.sql
-- Entidade: XpRegra
-- Tabela: xp_regras
-- Dependencias: nenhuma
-- =========================================================

CREATE TABLE IF NOT EXISTS xp_regras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(120) NOT NULL,
    tipo_regra VARCHAR(50) NOT NULL,
    xp_concedido INTEGER NOT NULL,
    percentual_bonus NUMERIC(8, 2),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    descricao VARCHAR(300),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_xp_regras PRIMARY KEY (id),
    CONSTRAINT uk_xp_regras_tipo_regra UNIQUE (tipo_regra),
    CONSTRAINT ck_xp_regras_tipo_regra CHECK (
        tipo_regra IN (
            'TREINO_COMPLETO', 'TREINO_SEM_VONTADE', 'PROGRESSAO_REAL', 'PROTEINA_DIARIA',
            'TREINOS_SEMANA', 'SONO_ADEQUADO', 'SONO_CONSISTENTE_SEMANA', 'RETORNO_APOS_PAUSA',
            'REGISTRO_DIARIO', 'SEMANA_COMPLETA_REGISTRADA', 'DIAS_TREINADOS_TOTAL',
            'PESO_ATINGIDO', 'CARGA_EXERCICIO_ATINGIDA', 'SEQUENCIA_ATUAL',
            'TREINOS_SEM_VONTADE_TOTAL', 'PROGRESSOES_TOTAL', 'ALIMENTACAO_ALINHADA',
            'DIAS_ALIMENTACAO_ALINHADA', 'RETORNOS_APOS_PAUSA_TOTAL', 'NIVEIS_SUBIDOS_TOTAL',
            'REGISTROS_SEMANA', 'NIVEL_ATUAL', 'XP_TOTAL'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_xp_regras_ativo_nome
    ON xp_regras (ativo, nome);

-- Carga inicial derivada do bootstrap da aplicacao
INSERT INTO xp_regras (nome, tipo_regra, xp_concedido, percentual_bonus, ativo, descricao, criado_em, atualizado_em)
VALUES
    ('Treino completo', 'TREINO_COMPLETO', 50, NULL, TRUE, 'Treino completo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Treino sem vontade', 'TREINO_SEM_VONTADE', 0, NULL, FALSE, 'Configurar percentual bonus sobre o XP-base do treino completo.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Progressao real', 'PROGRESSAO_REAL', 100, NULL, TRUE, 'Progressao real', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Proteina diaria', 'PROTEINA_DIARIA', 40, NULL, TRUE, 'Proteina diaria', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Cinco treinos na semana', 'TREINOS_SEMANA', 250, NULL, TRUE, 'Cinco treinos na semana', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Sono adequado', 'SONO_ADEQUADO', 30, NULL, TRUE, 'Sono adequado', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Sono consistente semanal', 'SONO_CONSISTENTE_SEMANA', 80, NULL, TRUE, 'Sono consistente semanal', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Retorno apos pausa', 'RETORNO_APOS_PAUSA', 250, NULL, TRUE, 'Retorno apos pausa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Registro diario', 'REGISTRO_DIARIO', 10, NULL, TRUE, 'Registro diario', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Semana completa registrada', 'SEMANA_COMPLETA_REGISTRADA', 50, NULL, TRUE, 'Semana completa registrada', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (tipo_regra) DO NOTHING;



-- =========================================================
-- Arquivo: missao_semanal.sql
-- Entidade: MissaoSemanal
-- Tabela: missoes_semanais
-- Dependencias: nenhuma
-- =========================================================

CREATE TABLE IF NOT EXISTS missoes_semanais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(120) NOT NULL,
    descricao VARCHAR(500),
    tipo_regra VARCHAR(50) NOT NULL,
    meta_valor NUMERIC(12, 2) NOT NULL,
    xp_recompensa INTEGER NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_missoes_semanais PRIMARY KEY (id),
    CONSTRAINT uk_missoes_semanais_nome UNIQUE (nome),
    CONSTRAINT ck_missoes_semanais_tipo_regra CHECK (
        tipo_regra IN (
            'TREINO_COMPLETO', 'TREINO_SEM_VONTADE', 'PROGRESSAO_REAL', 'PROTEINA_DIARIA',
            'TREINOS_SEMANA', 'SONO_ADEQUADO', 'SONO_CONSISTENTE_SEMANA', 'RETORNO_APOS_PAUSA',
            'REGISTRO_DIARIO', 'SEMANA_COMPLETA_REGISTRADA', 'DIAS_TREINADOS_TOTAL',
            'PESO_ATINGIDO', 'CARGA_EXERCICIO_ATINGIDA', 'SEQUENCIA_ATUAL',
            'TREINOS_SEM_VONTADE_TOTAL', 'PROGRESSOES_TOTAL', 'ALIMENTACAO_ALINHADA',
            'DIAS_ALIMENTACAO_ALINHADA', 'RETORNOS_APOS_PAUSA_TOTAL', 'NIVEIS_SUBIDOS_TOTAL',
            'REGISTROS_SEMANA', 'NIVEL_ATUAL', 'XP_TOTAL'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_missoes_semanais_ativo_nome
    ON missoes_semanais (ativo, nome);

CREATE INDEX IF NOT EXISTS idx_missoes_semanais_tipo_regra
    ON missoes_semanais (tipo_regra, ativo);

-- Carga inicial derivada do bootstrap da aplicacao
INSERT INTO missoes_semanais (nome, descricao, tipo_regra, meta_valor, xp_recompensa, ativo, criado_em, atualizado_em)
VALUES
    ('Treinar 5 dias', 'Treinar 5 dias', 'TREINOS_SEMANA', 5, 250, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Bater proteina diaria', 'Bater proteina diaria', 'PROTEINA_DIARIA', 5, 100, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Progredir carga ou reps', 'Progredir carga ou reps', 'PROGRESSAO_REAL', 1, 100, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Dormir 7-8 horas', 'Dormir 7-8 horas', 'SONO_CONSISTENTE_SEMANA', 5, 80, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Registrar o dia', 'Registrar o dia', 'REGISTROS_SEMANA', 5, 50, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (nome) DO NOTHING;



-- =========================================================
-- Arquivo: medalha.sql
-- Entidade: Medalha
-- Tabela: medalhas
-- Dependencias: nenhuma
-- =========================================================

CREATE TABLE IF NOT EXISTS medalhas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(120) NOT NULL,
    descricao VARCHAR(500),
    tipo VARCHAR(20) NOT NULL,
    tipo_regra VARCHAR(50) NOT NULL,
    valor_meta NUMERIC(12, 2) NOT NULL,
    valor_referencia VARCHAR(120),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_medalhas PRIMARY KEY (id),
    CONSTRAINT uk_medalhas_nome UNIQUE (nome),
    CONSTRAINT ck_medalhas_tipo CHECK (tipo IN ('UNICA', 'REPETIVEL')),
    CONSTRAINT ck_medalhas_tipo_regra CHECK (
        tipo_regra IN (
            'TREINO_COMPLETO', 'TREINO_SEM_VONTADE', 'PROGRESSAO_REAL', 'PROTEINA_DIARIA',
            'TREINOS_SEMANA', 'SONO_ADEQUADO', 'SONO_CONSISTENTE_SEMANA', 'RETORNO_APOS_PAUSA',
            'REGISTRO_DIARIO', 'SEMANA_COMPLETA_REGISTRADA', 'DIAS_TREINADOS_TOTAL',
            'PESO_ATINGIDO', 'CARGA_EXERCICIO_ATINGIDA', 'SEQUENCIA_ATUAL',
            'TREINOS_SEM_VONTADE_TOTAL', 'PROGRESSOES_TOTAL', 'ALIMENTACAO_ALINHADA',
            'DIAS_ALIMENTACAO_ALINHADA', 'RETORNOS_APOS_PAUSA_TOTAL', 'NIVEIS_SUBIDOS_TOTAL',
            'REGISTROS_SEMANA', 'NIVEL_ATUAL', 'XP_TOTAL'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_medalhas_ativo_nome
    ON medalhas (ativo, nome);

CREATE INDEX IF NOT EXISTS idx_medalhas_tipo_regra
    ON medalhas (tipo_regra, ativo);

-- Carga inicial derivada do bootstrap da aplicacao
INSERT INTO medalhas (nome, descricao, tipo, tipo_regra, valor_meta, valor_referencia, ativo, criado_em, atualizado_em)
VALUES
    ('3 meses', '3 meses', 'UNICA', 'DIAS_TREINADOS_TOTAL', 90, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('6 meses', '6 meses', 'UNICA', 'DIAS_TREINADOS_TOTAL', 180, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('1 ano', '1 ano', 'UNICA', 'DIAS_TREINADOS_TOTAL', 365, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('77kg atingido', '77kg atingido', 'UNICA', 'PESO_ATINGIDO', 77, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('80kg atingido', '80kg atingido', 'UNICA', 'PESO_ATINGIDO', 80, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Supino 30kg', 'Supino 30kg', 'UNICA', 'CARGA_EXERCICIO_ATINGIDA', 30, 'Supino', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Supino 40kg', 'Supino 40kg', 'UNICA', 'CARGA_EXERCICIO_ATINGIDA', 40, 'Supino', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Supino 50kg', 'Supino 50kg', 'UNICA', 'CARGA_EXERCICIO_ATINGIDA', 50, 'Supino', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Consistencia Brutal', 'Consistencia Brutal', 'REPETIVEL', 'SEQUENCIA_ATUAL', 15, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Treinei sem vontade', 'Treinei sem vontade', 'REPETIVEL', 'TREINOS_SEM_VONTADE_TOTAL', 1, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Progressao Real', 'Progressao Real', 'REPETIVEL', 'PROGRESSOES_TOTAL', 1, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Dieta Alinhada', 'Dieta Alinhada', 'REPETIVEL', 'DIAS_ALIMENTACAO_ALINHADA', 1, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Voltei Mais Forte', 'Voltei Mais Forte', 'REPETIVEL', 'RETORNOS_APOS_PAUSA_TOTAL', 1, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Subi de nivel', 'Subi de nivel', 'REPETIVEL', 'NIVEIS_SUBIDOS_TOTAL', 1, NULL, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (nome) DO NOTHING;



-- =========================================================
-- Arquivo: alimento.sql
-- Entidade: Alimento
-- Tabela: alimentos
-- Dependencias: nenhuma
-- =========================================================

CREATE TABLE IF NOT EXISTS alimentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(120) NOT NULL,
    calorias NUMERIC(10, 2) NOT NULL,
    proteina NUMERIC(10, 2) NOT NULL,
    carboidrato NUMERIC(10, 2) NOT NULL,
    gordura NUMERIC(10, 2) NOT NULL,
    acucares NUMERIC(10, 2) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_alimentos PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_alimentos_nome
    ON alimentos (nome);

CREATE INDEX IF NOT EXISTS idx_alimentos_lower_nome
    ON alimentos (LOWER(nome));

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: catalogo depende de input real/admin.



-- =========================================================
-- Arquivo: exercicio.sql
-- Entidade: Exercicio
-- Tabela: exercicios
-- Dependencias: nenhuma
-- =========================================================

CREATE TABLE IF NOT EXISTS exercicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(120) NOT NULL,
    grupo_muscular VARCHAR(60) NOT NULL,
    descricao VARCHAR(500),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_exercicios PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_exercicios_nome
    ON exercicios (nome);

CREATE INDEX IF NOT EXISTS idx_exercicios_lower_nome
    ON exercicios (LOWER(nome));

CREATE INDEX IF NOT EXISTS idx_exercicios_grupo_muscular
    ON exercicios (grupo_muscular);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: exercicios dependem de input real/admin.



-- =========================================================
-- Arquivo: treino.sql
-- Entidade: Treino
-- Tabela: treinos
-- Dependencias: usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS treinos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(120) NOT NULL,
    descricao VARCHAR(500),
    observacoes VARCHAR(500),
    tipo_treino VARCHAR(20) NOT NULL,
    usuario_id BIGINT NOT NULL,
    dia_semana VARCHAR(20),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    publico BOOLEAN NOT NULL DEFAULT FALSE,
    recorrente BOOLEAN NOT NULL DEFAULT TRUE,
    data_treino TIMESTAMP NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_treinos PRIMARY KEY (id),
    CONSTRAINT fk_treinos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT ck_treinos_tipo CHECK (tipo_treino IN ('A', 'B', 'C', 'FULL_BODY')),
    CONSTRAINT ck_treinos_dia_semana CHECK (
        dia_semana IS NULL OR dia_semana IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')
    )
);

CREATE INDEX IF NOT EXISTS idx_treinos_usuario_data
    ON treinos (usuario_id, data_treino DESC);

CREATE INDEX IF NOT EXISTS idx_treinos_usuario_ativo
    ON treinos (usuario_id, ativo, publico);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: treinos dependem de input real.



-- =========================================================
-- Arquivo: plano_alimentar.sql
-- Entidade: PlanoAlimentar
-- Tabela: planos_alimentares
-- Dependencias: usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS planos_alimentares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    nome VARCHAR(120) NOT NULL,
    descricao VARCHAR(500),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    publico BOOLEAN NOT NULL DEFAULT FALSE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_planos_alimentares PRIMARY KEY (id),
    CONSTRAINT fk_planos_alimentares_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE INDEX IF NOT EXISTS idx_planos_alimentares_usuario
    ON planos_alimentares (usuario_id, ativo);

CREATE INDEX IF NOT EXISTS idx_planos_alimentares_publico
    ON planos_alimentares (publico, ativo);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: plano alimentar depende de input real.



-- =========================================================
-- Arquivo: evolucao_fisica.sql
-- Entidade: EvolucaoFisica
-- Tabela: evolucoes_fisicas
-- Dependencias: usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS evolucoes_fisicas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    peso NUMERIC(10, 2) NOT NULL,
    percentual_gordura NUMERIC(10, 2),
    massa_magra NUMERIC(10, 2),
    data_registro TIMESTAMP NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_evolucoes_fisicas PRIMARY KEY (id),
    CONSTRAINT fk_evolucoes_fisicas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE INDEX IF NOT EXISTS idx_evolucoes_fisicas_usuario_data
    ON evolucoes_fisicas (usuario_id, data_registro DESC);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: evolucao fisica depende de input real.



-- =========================================================
-- Arquivo: meta_atleta.sql
-- Entidade: MetaAtleta
-- Tabela: metas_atletas
-- Dependencias: usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS metas_atletas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    frequencia_semanal_meta INTEGER,
    proteina_diaria_meta NUMERIC(10, 2),
    caloria_diaria_meta NUMERIC(10, 2),
    observacao VARCHAR(300),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_metas_atletas PRIMARY KEY (id),
    CONSTRAINT uk_metas_atletas_usuario UNIQUE (usuario_id),
    CONSTRAINT fk_metas_atletas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: metas dependem de input real do atleta.



-- =========================================================
-- Arquivo: perfil_gamificacao_usuario.sql
-- Entidade: PerfilGamificacaoUsuario
-- Tabela: perfis_gamificacao_usuarios
-- Dependencias: usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS perfis_gamificacao_usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    data_inicio DATE NOT NULL,
    peso_inicial NUMERIC(10, 2),
    peso_atual NUMERIC(10, 2),
    treinos_realizados INTEGER NOT NULL DEFAULT 0,
    sequencia_atual INTEGER NOT NULL DEFAULT 0,
    melhor_sequencia INTEGER NOT NULL DEFAULT 0,
    dias_treinados_total INTEGER NOT NULL DEFAULT 0,
    treinos_sem_vontade_total INTEGER NOT NULL DEFAULT 0,
    progressoes_total INTEGER NOT NULL DEFAULT 0,
    dias_alimentacao_alinhada INTEGER NOT NULL DEFAULT 0,
    retornos_apos_pausa_total INTEGER NOT NULL DEFAULT 0,
    niveis_subidos_total INTEGER NOT NULL DEFAULT 0,
    xp_total INTEGER NOT NULL DEFAULT 0,
    nivel_atual INTEGER NOT NULL DEFAULT 1,
    tier_atual VARCHAR(20) NOT NULL DEFAULT 'BRONZE',
    ultima_data_treino DATE,
    ultima_data_registro DATE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_perfis_gamificacao_usuarios PRIMARY KEY (id),
    CONSTRAINT uk_perfis_gamificacao_usuario UNIQUE (usuario_id),
    CONSTRAINT fk_perfis_gamificacao_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT ck_perfis_gamificacao_tier CHECK (tier_atual IN ('BRONZE', 'PRATA', 'OURO', 'LENDA'))
);

CREATE INDEX IF NOT EXISTS idx_perfis_gamificacao_ranking
    ON perfis_gamificacao_usuarios (xp_total DESC, nivel_atual DESC);

CREATE INDEX IF NOT EXISTS idx_perfis_gamificacao_tier
    ON perfis_gamificacao_usuarios (tier_atual, xp_total DESC);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: perfil e criado a partir de usuario real.


-- =========================================================
-- Arquivo: usuario_identidade_externa.sql
-- Entidade: UsuarioIdentidadeExterna
-- Tabela: usuarios_identidades_externas
-- Dependencias: usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS usuarios_identidades_externas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    provedor VARCHAR(30) NOT NULL,
    identificador_externo VARCHAR(150) NOT NULL,
    email_externo VARCHAR(150),
    nome_exibicao VARCHAR(120),
    foto_perfil_url VARCHAR(500),
    ultimo_login_em TIMESTAMP,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_usuarios_identidades_externas PRIMARY KEY (id),
    CONSTRAINT uk_provedor_identificador_externo UNIQUE (provedor, identificador_externo),
    CONSTRAINT fk_usuarios_identidades_externas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT ck_usuarios_identidades_externas_provedor CHECK (provedor IN ('GOOGLE'))
);

CREATE INDEX IF NOT EXISTS idx_usuarios_identidades_externas_usuario
    ON usuarios_identidades_externas (usuario_id);

CREATE INDEX IF NOT EXISTS idx_usuarios_identidades_externas_email
    ON usuarios_identidades_externas (email_externo);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: identidades externas dependem de vinculacao real.



-- =========================================================
-- Arquivo: seguidor.sql
-- Entidade: Seguidor
-- Tabela: seguidores
-- Dependencias: usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS seguidores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    seguidor_id BIGINT NOT NULL,
    seguido_id BIGINT NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_seguidores PRIMARY KEY (id),
    CONSTRAINT uk_seguidor_seguido UNIQUE (seguidor_id, seguido_id),
    CONSTRAINT fk_seguidores_seguidor FOREIGN KEY (seguidor_id) REFERENCES usuarios (id),
    CONSTRAINT fk_seguidores_seguido FOREIGN KEY (seguido_id) REFERENCES usuarios (id)
);

CREATE INDEX IF NOT EXISTS idx_seguidores_seguidor_ativo
    ON seguidores (seguidor_id, ativo);

CREATE INDEX IF NOT EXISTS idx_seguidores_seguido_ativo
    ON seguidores (seguido_id, ativo);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: relacionamentos sociais dependem de evento real.



-- =========================================================
-- Arquivo: grupo.sql
-- Entidade: Grupo
-- Tabela: grupos
-- Dependencias: usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS grupos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(120) NOT NULL,
    descricao VARCHAR(500),
    criador_id BIGINT NOT NULL,
    visibilidade VARCHAR(20) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_grupos PRIMARY KEY (id),
    CONSTRAINT fk_grupos_criador FOREIGN KEY (criador_id) REFERENCES usuarios (id),
    CONSTRAINT ck_grupos_visibilidade CHECK (visibilidade IN ('PUBLICA', 'SEGUIDORES', 'GRUPO', 'PRIVADA'))
);

CREATE INDEX IF NOT EXISTS idx_grupos_criador_ativo
    ON grupos (criador_id, ativo);

CREATE INDEX IF NOT EXISTS idx_grupos_visibilidade_ativo
    ON grupos (visibilidade, ativo);

CREATE INDEX IF NOT EXISTS idx_grupos_nome
    ON grupos (nome);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: grupos dependem de input real do usuario.



-- =========================================================
-- Arquivo: treino_exercicio.sql
-- Entidade: TreinoExercicio
-- Tabela: treino_exercicios
-- Dependencias: treinos, exercicios
-- =========================================================

CREATE TABLE IF NOT EXISTS treino_exercicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    treino_id BIGINT NOT NULL,
    exercicio_id BIGINT NOT NULL,
    series INTEGER NOT NULL,
    repeticoes INTEGER NOT NULL,
    carga NUMERIC(10, 2),
    dificuldade VARCHAR(20) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_treino_exercicios PRIMARY KEY (id),
    CONSTRAINT fk_treino_exercicios_treino FOREIGN KEY (treino_id) REFERENCES treinos (id),
    CONSTRAINT fk_treino_exercicios_exercicio FOREIGN KEY (exercicio_id) REFERENCES exercicios (id),
    CONSTRAINT ck_treino_exercicios_dificuldade CHECK (dificuldade IN ('LEVE', 'MODERADA', 'ALTA'))
);

CREATE INDEX IF NOT EXISTS idx_treino_exercicios_treino
    ON treino_exercicios (treino_id, id);

CREATE INDEX IF NOT EXISTS idx_treino_exercicios_exercicio
    ON treino_exercicios (exercicio_id);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: associacao depende de input real.



-- =========================================================
-- Arquivo: plano_alimentar_dia.sql
-- Entidade: PlanoAlimentarDia
-- Tabela: planos_alimentares_dias
-- Dependencias: planos_alimentares
-- =========================================================

CREATE TABLE IF NOT EXISTS planos_alimentares_dias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    plano_id BIGINT NOT NULL,
    dia_semana VARCHAR(20) NOT NULL,
    titulo VARCHAR(120) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_planos_alimentares_dias PRIMARY KEY (id),
    CONSTRAINT fk_planos_alimentares_dias_plano FOREIGN KEY (plano_id) REFERENCES planos_alimentares (id),
    CONSTRAINT ck_planos_alimentares_dias_dia_semana CHECK (
        dia_semana IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')
    )
);

CREATE INDEX IF NOT EXISTS idx_planos_alimentares_dias_plano_dia
    ON planos_alimentares_dias (plano_id, dia_semana);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: dias do plano dependem de input real.



-- =========================================================
-- Arquivo: registro_diario.sql
-- Entidade: RegistroDiario
-- Tabela: registros_diarios
-- Dependencias: usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS registros_diarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    data_referencia DATE NOT NULL,
    realizou_treino BOOLEAN NOT NULL DEFAULT FALSE,
    tipo_treino VARCHAR(120),
    peso NUMERIC(10, 2),
    proteina_consumida NUMERIC(10, 2),
    bateu_proteina BOOLEAN NOT NULL DEFAULT FALSE,
    alimentacao_alinhada BOOLEAN NOT NULL DEFAULT FALSE,
    horas_sono NUMERIC(4, 2),
    houve_progressao BOOLEAN NOT NULL DEFAULT FALSE,
    descricao_progressao VARCHAR(500),
    motivacao VARCHAR(20) NOT NULL DEFAULT 'MEDIA',
    observacao VARCHAR(1000),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_registros_diarios PRIMARY KEY (id),
    CONSTRAINT uk_registro_diario_usuario_data UNIQUE (usuario_id, data_referencia),
    CONSTRAINT fk_registros_diarios_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT ck_registros_diarios_motivacao CHECK (motivacao IN ('ALTA', 'MEDIA', 'BAIXA'))
);

CREATE INDEX IF NOT EXISTS idx_registros_diarios_usuario_motivacao_treino
    ON registros_diarios (usuario_id, motivacao, realizou_treino);

CREATE INDEX IF NOT EXISTS idx_registros_diarios_usuario_progressao
    ON registros_diarios (usuario_id, houve_progressao);

CREATE INDEX IF NOT EXISTS idx_registros_diarios_usuario_alimentacao
    ON registros_diarios (usuario_id, alimentacao_alinhada);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: registros diarios dependem de input real.



-- =========================================================
-- Arquivo: usuario_medalha.sql
-- Entidade: UsuarioMedalha
-- Tabela: usuarios_medalhas
-- Dependencias: usuarios, medalhas
-- =========================================================

CREATE TABLE IF NOT EXISTS usuarios_medalhas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    medalha_id BIGINT NOT NULL,
    quantidade INTEGER NOT NULL DEFAULT 0,
    ultima_conquista_em TIMESTAMP,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_usuarios_medalhas PRIMARY KEY (id),
    CONSTRAINT uk_usuario_medalha UNIQUE (usuario_id, medalha_id),
    CONSTRAINT fk_usuarios_medalhas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_usuarios_medalhas_medalha FOREIGN KEY (medalha_id) REFERENCES medalhas (id)
);

CREATE INDEX IF NOT EXISTS idx_usuarios_medalhas_usuario
    ON usuarios_medalhas (usuario_id, ultima_conquista_em DESC);

CREATE INDEX IF NOT EXISTS idx_usuarios_medalhas_medalha
    ON usuarios_medalhas (medalha_id);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: concessao depende de evento real.



-- =========================================================
-- Arquivo: usuario_missao_semanal.sql
-- Entidade: UsuarioMissaoSemanal
-- Tabela: usuarios_missoes_semanais
-- Dependencias: usuarios, missoes_semanais
-- =========================================================

CREATE TABLE IF NOT EXISTS usuarios_missoes_semanais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    missao_id BIGINT NOT NULL,
    semana_referencia DATE NOT NULL,
    progresso NUMERIC(12, 2) NOT NULL DEFAULT 0,
    concluida BOOLEAN NOT NULL DEFAULT FALSE,
    total_conclusoes INTEGER NOT NULL DEFAULT 0,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_usuarios_missoes_semanais PRIMARY KEY (id),
    CONSTRAINT uk_usuario_missao_semana UNIQUE (usuario_id, missao_id, semana_referencia),
    CONSTRAINT fk_usuarios_missoes_semanais_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_usuarios_missoes_semanais_missao FOREIGN KEY (missao_id) REFERENCES missoes_semanais (id)
);

CREATE INDEX IF NOT EXISTS idx_usuarios_missoes_semanais_usuario_semana
    ON usuarios_missoes_semanais (usuario_id, semana_referencia);

CREATE INDEX IF NOT EXISTS idx_usuarios_missoes_semanais_missao_semana
    ON usuarios_missoes_semanais (missao_id, semana_referencia);

CREATE INDEX IF NOT EXISTS idx_usuarios_missoes_semanais_concluida
    ON usuarios_missoes_semanais (usuario_id, missao_id, concluida);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: progresso semanal depende de evento real.



-- =========================================================
-- Arquivo: xp_transacao.sql
-- Entidade: XpTransacao
-- Tabela: xp_transacoes
-- Dependencias: usuarios, xp_regras, registros_diarios, registros_treino
-- =========================================================

CREATE TABLE IF NOT EXISTS xp_transacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    regra_id BIGINT,
    registro_diario_id BIGINT,
    registro_treino_id BIGINT,
    valor INTEGER NOT NULL,
    descricao VARCHAR(150) NOT NULL,
    referencia_unica VARCHAR(150) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_xp_transacoes PRIMARY KEY (id),
    CONSTRAINT uk_xp_usuario_referencia UNIQUE (usuario_id, referencia_unica),
    CONSTRAINT fk_xp_transacoes_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_xp_transacoes_regra FOREIGN KEY (regra_id) REFERENCES xp_regras (id),
    CONSTRAINT fk_xp_transacoes_registro_diario FOREIGN KEY (registro_diario_id) REFERENCES registros_diarios (id),
    CONSTRAINT fk_xp_transacoes_registro_treino FOREIGN KEY (registro_treino_id) REFERENCES registros_treino (id)
);

CREATE INDEX IF NOT EXISTS idx_xp_transacoes_usuario_criado_em
    ON xp_transacoes (usuario_id, criado_em DESC);

CREATE INDEX IF NOT EXISTS idx_xp_transacoes_regra
    ON xp_transacoes (regra_id);

CREATE INDEX IF NOT EXISTS idx_xp_transacoes_registro_diario
    ON xp_transacoes (registro_diario_id);

CREATE INDEX IF NOT EXISTS idx_xp_transacoes_registro_treino
    ON xp_transacoes (registro_treino_id);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: historico de XP depende de evento real persistido.



-- =========================================================
-- Arquivo: registro_treino.sql
-- Entidade: RegistroTreino
-- Tabela: registros_treino
-- Dependencias: usuarios, treinos
-- =========================================================

CREATE TABLE IF NOT EXISTS registros_treino (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    treino_id BIGINT NOT NULL,
    data_registro TIMESTAMP NOT NULL,
    finalizado_em TIMESTAMP,
    observacao VARCHAR(500),
    motivacao VARCHAR(20),
    concluido BOOLEAN NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_registros_treino PRIMARY KEY (id),
    CONSTRAINT fk_registros_treino_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_registros_treino_treino FOREIGN KEY (treino_id) REFERENCES treinos (id),
    CONSTRAINT ck_registros_treino_motivacao CHECK (
        motivacao IS NULL OR motivacao IN ('ALTA', 'MEDIA', 'BAIXA')
    )
);

CREATE INDEX IF NOT EXISTS idx_registros_treino_usuario_data
    ON registros_treino (usuario_id, data_registro DESC);

CREATE INDEX IF NOT EXISTS idx_registros_treino_usuario_concluido_data
    ON registros_treino (usuario_id, concluido, data_registro ASC);

CREATE INDEX IF NOT EXISTS idx_registros_treino_treino
    ON registros_treino (treino_id);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: registros de treino dependem de evento real.



-- =========================================================
-- Arquivo: refeicao.sql
-- Entidade: Refeicao
-- Tabela: refeicoes
-- Dependencias: usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS refeicoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    data TIMESTAMP NOT NULL,
    tipo VARCHAR(30) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_refeicoes PRIMARY KEY (id),
    CONSTRAINT fk_refeicoes_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT ck_refeicoes_tipo CHECK (
        tipo IN (
            'CAFE_DA_MANHA', 'CAFE_DA_TARDE', 'ALMOCO', 'JANTAR',
            'LANCHE', 'CEIA', 'PRE_TREINO', 'POS_TREINO'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_refeicoes_usuario_data
    ON refeicoes (usuario_id, data DESC);

CREATE INDEX IF NOT EXISTS idx_refeicoes_usuario_tipo_data
    ON refeicoes (usuario_id, tipo, data DESC);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: refeicoes dependem de input real.



-- =========================================================
-- Arquivo: grupo_membro.sql
-- Entidade: GrupoMembro
-- Tabela: grupos_membros
-- Dependencias: grupos, usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS grupos_membros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    grupo_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    role VARCHAR(20) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_grupos_membros PRIMARY KEY (id),
    CONSTRAINT uk_grupo_usuario UNIQUE (grupo_id, usuario_id),
    CONSTRAINT fk_grupos_membros_grupo FOREIGN KEY (grupo_id) REFERENCES grupos (id),
    CONSTRAINT fk_grupos_membros_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT ck_grupos_membros_role CHECK (role IN ('DONO', 'ADMIN', 'MEMBRO'))
);

CREATE INDEX IF NOT EXISTS idx_grupos_membros_usuario_ativo
    ON grupos_membros (usuario_id, ativo);

CREATE INDEX IF NOT EXISTS idx_grupos_membros_grupo_ativo
    ON grupos_membros (grupo_id, ativo);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: vinculo depende de evento real do usuario.



-- =========================================================
-- Arquivo: postagem.sql
-- Entidade: Postagem
-- Tabela: postagens
-- Dependencias: usuarios, grupos, registros_treino, evolucoes_fisicas
-- =========================================================

CREATE TABLE IF NOT EXISTS postagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    autor_id BIGINT NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    visibilidade VARCHAR(20) NOT NULL,
    grupo_id BIGINT,
    registro_treino_id BIGINT,
    evolucao_fisica_id BIGINT,
    conteudo VARCHAR(2000),
    midia_url VARCHAR(500),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_postagens PRIMARY KEY (id),
    CONSTRAINT fk_postagens_autor FOREIGN KEY (autor_id) REFERENCES usuarios (id),
    CONSTRAINT fk_postagens_grupo FOREIGN KEY (grupo_id) REFERENCES grupos (id),
    CONSTRAINT fk_postagens_registro_treino FOREIGN KEY (registro_treino_id) REFERENCES registros_treino (id),
    CONSTRAINT fk_postagens_evolucao_fisica FOREIGN KEY (evolucao_fisica_id) REFERENCES evolucoes_fisicas (id),
    CONSTRAINT ck_postagens_tipo CHECK (tipo IN ('TREINO', 'DIETA', 'EVOLUCAO', 'TEXTO', 'FOTO')),
    CONSTRAINT ck_postagens_visibilidade CHECK (visibilidade IN ('PUBLICA', 'SEGUIDORES', 'GRUPO', 'PRIVADA'))
);

CREATE INDEX IF NOT EXISTS idx_postagens_autor_criado_em
    ON postagens (autor_id, criado_em DESC);

CREATE INDEX IF NOT EXISTS idx_postagens_grupo_criado_em
    ON postagens (grupo_id, criado_em DESC);

CREATE INDEX IF NOT EXISTS idx_postagens_visibilidade_ativo
    ON postagens (visibilidade, ativo, criado_em DESC);

CREATE INDEX IF NOT EXISTS idx_postagens_registro_treino
    ON postagens (registro_treino_id);

CREATE INDEX IF NOT EXISTS idx_postagens_evolucao_fisica
    ON postagens (evolucao_fisica_id);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: postagens dependem de evento real.



-- =========================================================
-- Arquivo: plano_alimentar_refeicao.sql
-- Entidade: PlanoAlimentarRefeicao
-- Tabela: planos_alimentares_refeicoes
-- Dependencias: planos_alimentares_dias
-- =========================================================

CREATE TABLE IF NOT EXISTS planos_alimentares_refeicoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    plano_dia_id BIGINT NOT NULL,
    tipo_refeicao VARCHAR(30) NOT NULL,
    horario_sugerido TIME,
    observacao VARCHAR(500),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_planos_alimentares_refeicoes PRIMARY KEY (id),
    CONSTRAINT fk_planos_alimentares_refeicoes_dia FOREIGN KEY (plano_dia_id) REFERENCES planos_alimentares_dias (id),
    CONSTRAINT ck_planos_alimentares_refeicoes_tipo CHECK (
        tipo_refeicao IN (
            'CAFE_DA_MANHA', 'CAFE_DA_TARDE', 'ALMOCO', 'JANTAR',
            'LANCHE', 'CEIA', 'PRE_TREINO', 'POS_TREINO'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_planos_alimentares_refeicoes_dia_tipo
    ON planos_alimentares_refeicoes (plano_dia_id, tipo_refeicao);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: refeicoes do plano dependem de input real.



-- =========================================================
-- Arquivo: registro_exercicio.sql
-- Entidade: RegistroExercicio
-- Tabela: registro_exercicios
-- Dependencias: registros_treino, exercicios
-- =========================================================

CREATE TABLE IF NOT EXISTS registro_exercicios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    registro_treino_id BIGINT NOT NULL,
    exercicio_id BIGINT NOT NULL,
    carga_real NUMERIC(10, 2),
    repeticoes_real INTEGER NOT NULL,
    concluido BOOLEAN NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_registro_exercicios PRIMARY KEY (id),
    CONSTRAINT fk_registro_exercicios_registro_treino FOREIGN KEY (registro_treino_id) REFERENCES registros_treino (id),
    CONSTRAINT fk_registro_exercicios_exercicio FOREIGN KEY (exercicio_id) REFERENCES exercicios (id)
);

CREATE INDEX IF NOT EXISTS idx_registro_exercicios_registro
    ON registro_exercicios (registro_treino_id, id);

CREATE INDEX IF NOT EXISTS idx_registro_exercicios_exercicio
    ON registro_exercicios (exercicio_id);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: execucao depende de evento real.



-- =========================================================
-- Arquivo: refeicao_alimento.sql
-- Entidade: RefeicaoAlimento
-- Tabela: refeicao_alimentos
-- Dependencias: refeicoes, alimentos
-- =========================================================

CREATE TABLE IF NOT EXISTS refeicao_alimentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    refeicao_id BIGINT NOT NULL,
    alimento_id BIGINT NOT NULL,
    quantidade NUMERIC(10, 2) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_refeicao_alimentos PRIMARY KEY (id),
    CONSTRAINT fk_refeicao_alimentos_refeicao FOREIGN KEY (refeicao_id) REFERENCES refeicoes (id),
    CONSTRAINT fk_refeicao_alimentos_alimento FOREIGN KEY (alimento_id) REFERENCES alimentos (id)
);

CREATE INDEX IF NOT EXISTS idx_refeicao_alimentos_refeicao
    ON refeicao_alimentos (refeicao_id);

CREATE INDEX IF NOT EXISTS idx_refeicao_alimentos_alimento
    ON refeicao_alimentos (alimento_id);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: composicao da refeicao depende de input real.



-- =========================================================
-- Arquivo: postagem_comentario.sql
-- Entidade: PostagemComentario
-- Tabela: postagens_comentarios
-- Dependencias: postagens, usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS postagens_comentarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    postagem_id BIGINT NOT NULL,
    autor_id BIGINT NOT NULL,
    conteudo VARCHAR(1000) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_postagens_comentarios PRIMARY KEY (id),
    CONSTRAINT fk_postagens_comentarios_postagem FOREIGN KEY (postagem_id) REFERENCES postagens (id),
    CONSTRAINT fk_postagens_comentarios_autor FOREIGN KEY (autor_id) REFERENCES usuarios (id)
);

CREATE INDEX IF NOT EXISTS idx_postagens_comentarios_postagem_criado_em
    ON postagens_comentarios (postagem_id, criado_em ASC);

CREATE INDEX IF NOT EXISTS idx_postagens_comentarios_autor_criado_em
    ON postagens_comentarios (autor_id, criado_em DESC);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: comentarios dependem de input real.



-- =========================================================
-- Arquivo: postagem_curtida.sql
-- Entidade: PostagemCurtida
-- Tabela: postagens_curtidas
-- Dependencias: postagens, usuarios
-- =========================================================

CREATE TABLE IF NOT EXISTS postagens_curtidas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    postagem_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_postagens_curtidas PRIMARY KEY (id),
    CONSTRAINT uk_postagem_usuario_curtida UNIQUE (postagem_id, usuario_id),
    CONSTRAINT fk_postagens_curtidas_postagem FOREIGN KEY (postagem_id) REFERENCES postagens (id),
    CONSTRAINT fk_postagens_curtidas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id)
);

CREATE INDEX IF NOT EXISTS idx_postagens_curtidas_usuario
    ON postagens_curtidas (usuario_id);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: curtidas dependem de evento real.



-- =========================================================
-- Arquivo: plano_alimentar_refeicao_alimento.sql
-- Entidade: PlanoAlimentarRefeicaoAlimento
-- Tabela: planos_alimentares_refeicoes_alimentos
-- Dependencias: planos_alimentares_refeicoes, alimentos
-- =========================================================

CREATE TABLE IF NOT EXISTS planos_alimentares_refeicoes_alimentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    plano_refeicao_id BIGINT NOT NULL,
    alimento_id BIGINT NOT NULL,
    quantidade NUMERIC(10, 2) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_planos_alimentares_refeicoes_alimentos PRIMARY KEY (id),
    CONSTRAINT fk_planos_alimentares_refeicoes_alimentos_refeicao FOREIGN KEY (plano_refeicao_id) REFERENCES planos_alimentares_refeicoes (id),
    CONSTRAINT fk_planos_alimentares_refeicoes_alimentos_alimento FOREIGN KEY (alimento_id) REFERENCES alimentos (id)
);

CREATE INDEX IF NOT EXISTS idx_planos_alimentares_refeicoes_alimentos_refeicao
    ON planos_alimentares_refeicoes_alimentos (plano_refeicao_id);

CREATE INDEX IF NOT EXISTS idx_planos_alimentares_refeicoes_alimentos_alimento
    ON planos_alimentares_refeicoes_alimentos (alimento_id);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: composicao do plano depende de input real.



