DROP TABLE IF EXISTS xp_regras CASCADE;

-- =========================================================
-- Arquivo: xp_regra.sql
-- Entidade: XpRegra
-- Tabela: xp_regras
-- Dependencias: nenhuma
-- =========================================================

CREATE TABLE IF NOT EXISTS xp_regras (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(120) NOT NULL,
    tipo_regra VARCHAR(50) NOT NULL,
    xp_concedido INTEGER NOT NULL,
    percentual_bonus NUMERIC(8, 2),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    descricao VARCHAR(300),
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_xp_regras PRIMARY KEY (id),
    CONSTRAINT uk_xp_regras_tipo_regra UNIQUE (tipo_regra),
    CONSTRAINT ck_xp_regras_tipo_regra CHECK (
        tipo_regra IN (
            'TREINO_COMPLETO', 'TREINO_SEM_VONTADE', 'PROGRESSAO_REAL', 'PROTEINA_DIARIA',
            'TREINOS_SEMANA', 'SONO_ADEQUADO', 'SONO_CONSISTENTE_SEMANA', 'RETORNO_APOS_PAUSA',
            'REGISTRO_DIARIO', 'SEMANA_COMPLETA_REGISTRADA', 'DIAS_TREINADOS_TOTAL',
            'PESO_ATINGIDO', 'CARGA_EXERCICIO_ATINGIDA', 'SEQUENCIA_ATUAL',
            'TREINOS_SEM_VONTADE_TOTAL', 'PROGRESSOES_TOTAL', 'ALIMENTACAO_ALINHADA',
            'DIAS_ALIMENTACAO_ALINHADA', 'RETORNOS_APOS_PAUSA_TOTAL', 'NIVEIS_SUBIDOS_TOTAL',
            'REGISTROS_SEMANA', 'NIVEL_ATUAL', 'XP_TOTAL'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_xp_regras_ativo_nome
    ON xp_regras (ativo, nome);

-- Carga inicial derivada do bootstrap da aplicacao
INSERT INTO xp_regras (nome, tipo_regra, xp_concedido, percentual_bonus, ativo, descricao, criado_em, atualizado_em)
VALUES
    ('Treino completo', 'TREINO_COMPLETO', 50, NULL, TRUE, 'Treino completo', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Treino sem vontade', 'TREINO_SEM_VONTADE', 0, NULL, FALSE, 'Configurar percentual bonus sobre o XP-base do treino completo.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Progressao real', 'PROGRESSAO_REAL', 100, NULL, TRUE, 'Progressao real', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Proteina diaria', 'PROTEINA_DIARIA', 40, NULL, TRUE, 'Proteina diaria', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Cinco treinos na semana', 'TREINOS_SEMANA', 250, NULL, TRUE, 'Cinco treinos na semana', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Sono adequado', 'SONO_ADEQUADO', 30, NULL, TRUE, 'Sono adequado', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Sono consistente semanal', 'SONO_CONSISTENTE_SEMANA', 80, NULL, TRUE, 'Sono consistente semanal', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Retorno apos pausa', 'RETORNO_APOS_PAUSA', 250, NULL, TRUE, 'Retorno apos pausa', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Registro diario', 'REGISTRO_DIARIO', 10, NULL, TRUE, 'Registro diario', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Semana completa registrada', 'SEMANA_COMPLETA_REGISTRADA', 50, NULL, TRUE, 'Semana completa registrada', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (tipo_regra) DO NOTHING;


