-- =========================================================
-- Arquivo: xp_transacao.sql
-- Entidade: XpTransacao
-- Tabela: xp_transacoes
-- Dependencias: usuarios, xp_regras, registros_diarios, registros_treino
-- =========================================================

CREATE TABLE IF NOT EXISTS xp_transacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id BIGINT NOT NULL,
    regra_id BIGINT,
    registro_diario_id BIGINT,
    registro_treino_id BIGINT,
    valor INTEGER NOT NULL,
    descricao VARCHAR(150) NOT NULL,
    referencia_unica VARCHAR(150) NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_xp_transacoes PRIMARY KEY (id),
    CONSTRAINT uk_xp_usuario_referencia UNIQUE (usuario_id, referencia_unica),
    CONSTRAINT fk_xp_transacoes_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_xp_transacoes_regra FOREIGN KEY (regra_id) REFERENCES xp_regras (id),
    CONSTRAINT fk_xp_transacoes_registro_diario FOREIGN KEY (registro_diario_id) REFERENCES registros_diarios (id),
    CONSTRAINT fk_xp_transacoes_registro_treino FOREIGN KEY (registro_treino_id) REFERENCES registros_treino (id)
);

CREATE INDEX IF NOT EXISTS idx_xp_transacoes_usuario_criado_em
    ON xp_transacoes (usuario_id, criado_em DESC);

CREATE INDEX IF NOT EXISTS idx_xp_transacoes_regra
    ON xp_transacoes (regra_id);

CREATE INDEX IF NOT EXISTS idx_xp_transacoes_registro_diario
    ON xp_transacoes (registro_diario_id);

CREATE INDEX IF NOT EXISTS idx_xp_transacoes_registro_treino
    ON xp_transacoes (registro_treino_id);

-- Carga inicial
-- Nenhuma carga inicial obrigatoria: historico de XP depende de evento real persistido.

